# Generated by Django 5.0 on 2023-12-14 14:19

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE SCHEMA IF NOT EXISTS content;
            """,
            reverse_sql='DROP SCHEMA content CASCADE;',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated'),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.TextField(verbose_name='name')),
                (
                    'number',
                    models.CharField(max_length=20, verbose_name='number'),
                ),
                ('day_cost', models.FloatField(verbose_name='day_cost')),
                (
                    'travellers',
                    models.FloatField(
                        blank=True, null=True, verbose_name='travellers'
                    ),
                ),
                (
                    'rating',
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='rating',
                    ),
                ),
                (
                    'refundable',
                    models.BooleanField(
                        default=True, verbose_name='refundable'
                    ),
                ),
                (
                    'sleeping_area',
                    models.TextField(
                        choices=[
                            ('twin', 'Twin'),
                            ('double', 'Double'),
                            ('twin_bunk', 'Twinbunk'),
                            ('double_twin_bunk', 'Doubletwinbunk'),
                        ],
                        default='twin',
                        verbose_name='sleeping_area',
                    ),
                ),
                (
                    'free',
                    models.BooleanField(default=True, verbose_name='free'),
                ),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'content"."rooms',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated'),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'starting_date',
                    models.DateTimeField(verbose_name='starting_date'),
                ),
                (
                    'ending_date',
                    models.DateTimeField(verbose_name='ending_date'),
                ),
                (
                    'active',
                    models.BooleanField(default=True, verbose_name='active'),
                ),
                (
                    'rentler',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reservations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'content"."reservations',
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(
                fields=('name', 'number'), name='name_number_constraint'
            ),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reservations',
                to='rooms.room',
            ),
        ),
    ]
