# Generated by Django 5.0 on 2023-12-17 08:54

from django.db import migrations, models

import rooms.models


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation', old_name='rentler', new_name='user',
        ),
        migrations.RemoveField(model_name='reservation', name='active',),
        migrations.RemoveField(model_name='room', name='free',),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.TextField(
                choices=[
                    ('booked', 'Booked'),
                    ('refused', 'Refused'),
                    ('active', 'Active'),
                ],
                default='booked',
                verbose_name='status',
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ending_date',
            field=models.DateTimeField(
                validators=[
                    rooms.models.Reservation.validate_date_within_two_weeks,
                    rooms.models.Reservation.validate_future_date,
                ],
                verbose_name='ending_date',
            ),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='starting_date',
            field=models.DateTimeField(
                validators=[
                    rooms.models.Reservation.validate_date_within_two_weeks,
                    rooms.models.Reservation.validate_future_date,
                ],
                verbose_name='starting_date',
            ),
        ),
    ]
